Mini-Project:
Data Preprocessing Math & Feature Scaling Engine


Structure of project:

1. Synthetic Dataset generation: making numeric features (like house price, age, salary) form using numpy.

2. Custom Normalizer & Standardizer:
By use of numpy vectorization (axis = 0)

3. Before vs After Statistics:
(mean, std, min, max) ater comaparison of all of that printing project's output.

In [2]:
# Importing numpy:
import numpy as np


In [3]:
# Set seed for reproductivity:
np.random.seed(42)


1. Data Simulation:


In [4]:
# Creating a dummy dataset:
age = np.random.randint(20, 60, size = (5, 1))
salary = np.random.randint(30000, 150000, size = (5, 1))
house_price = np.random.randint(100000, 500000, size = (5, 1))


# combine columns horizonatally to make a 2D dataset:
dataset = np.hstack((age, salary, house_price))


In [12]:
print("--- RAW DATASET ---")
print("Columns: \n[Age, Salary, House Price]")
print(dataset)
print("-"*50)

--- RAW DATASET ---
Columns: 
[Age, Salary, House Price]
[[    58  84886 474871]
 [    48  36265 488468]
 [    34 112386 275203]
 [    27  67194 291335]
 [    40 117498 378167]]
--------------------------------------------------


2. Min-Max Normalization

In [6]:
# Applying Min-Max normalization (0 and 1):
'''
Formula: X_new = (X - X_min) / (X_max - X_min)

where:
X_new = Min-Max normalization,
X_min = small element of X
X_max = big element of X
X = dataset
'''

def min_max_normalize(data):
  min_data = data.min(axis = 0)
  max_data = data.max(axis = 0)

  # Handle division by 0 if maximum = minimum
  range_data = np.where(max_data - min_data == 0, 1, max_data - min_data)
  return (data - min_data)/ range_data

normalized_dataset = min_max_normalize(dataset)


In [7]:
print("\n--- MIN-MAX NORMALIZED DATA ---")
print(np.round(normalized_dataset, 4))
print("-"*50)


--- MIN-MAX NORMALIZED DATA ---
[[1.     0.5985 0.9362]
 [0.6774 0.     1.    ]
 [0.2258 0.9371 0.    ]
 [0.     0.3807 0.0756]
 [0.4194 1.     0.4828]]
--------------------------------------------------


3. Z-Score Standaridzation (Mean = 0, Std Dev = 1)

In [8]:
from os import scandir
# Apply Standardization(z-Score) fucntion:
'''
Formula: Z = X - X_mean / X_std

where:
Z = Standardization
X = data
X_mean = mean of data
X_std = std of data
'''

def z_score_standardization(data):
  mean_data = data.mean(axis = 0)
  std_data = data.std(axis = 0)

  # Handle division by 0 if std is zero
  std_data = np.where(std_data == 0, 1, std_data)
  return (data - mean_data) / std_data

standardized_data = z_score_standardization(dataset)


In [9]:
print("\n--- Z-SCORE STANDARDIZED DATA ---")
print(np.round(standardized_data, 4))
print("-"*50)


--- Z-SCORE STANDARDIZED DATA ---
[[ 1.537   0.0414  1.048 ]
 [ 0.6111 -1.5813  1.2007]
 [-0.6852  0.9592 -1.1956]
 [-1.3333 -0.5491 -1.0144]
 [-0.1296  1.1298 -0.0387]]
--------------------------------------------------


4. Verification of properties

In [11]:
print("\n--- VERIFICATION ---")
print("Standarized Mean (Should be close to 0):", np.round(standardized_data.mean(axis = 0), 4))
print("Standarized Std Dev (should be 1):", np.round(standardized_data.std(axis = 0), 4))



--- VERIFICATION ---
Standarized Mean (Should be close to 0): [ 0. -0.  0.]
Standarized Std Dev (should be 1): [1. 1. 1.]
